ENH-353-initialisation of mixed profiles on creation
gambitproject/gambit pull request #368
Opened 2023-10-02 09:44 UTC by VarsosC

2023-10-05 10:15 UTC, tturocy commented on src/pygambit/game.pxi
> +        """Returns a behavior strategy profile `MixedBehaviorProfile` over the game,
I think it's useful as a convention to try to keep the first sentence of the docstring concise, as that's what the user will see first in the documentation.  Then after a blank line, we can be more verbose about the operation of the function.  This is the general pattern numpy/scipy/pandas &c follow.

2023-10-05 10:15 UTC, tturocy commented on src/pygambit/game.pxi
> +        initialized to uniform randomization for each player over his actions at each
The docstring repeats itself; it should say what happens when `data` are specified.

2023-10-05 10:15 UTC, tturocy commented on src/pygambit/game.pxi
> +            If `True`, probabilities are represented using rational numbers; otherwise
It appears that numpydoc convention is that when referring to Python constants like True, False, None and so on, not to enclose them in any back-ticks at all (as in the original version of the docstring)

2023-10-05 10:15 UTC, tturocy commented on src/pygambit/game.pxi
> +                if data is None:
A mixed behavior profile is a probability distribution over actions, not nodes.   So the `data` parameter should have the same dimension as the (nested) tuples of (player, infoset, action).  That is, the top level should have length equal to number of players, then for each player, the level should have length equal to that player's number of information sets, and then for each information set, equal to the number of actions.

2023-10-05 10:15 UTC, tturocy commented on src/pygambit/tests/test_behav.py
> +        self.profile_rational = self.game.mixed_behavior_profile(None, True)
It would be useful to add a test of creating the behavior profile set to a specific distribution, exercising the new code.

2023-10-05 10:16 UTC, tturocy requested changes
Please see the individual comments for suggestions/requests.

2023-10-05 10:21 UTC, VarsosC commented
Thanks for the suggestions and the requests.

2023-10-30 13:31 UTC, tturocy requested changes
Currently this pull request has no changes at all (other than changing whether src/pygambit/game.pxi has a newline at the end of the file, and adds a superfluous `import pygambit` at the start of `test_behav.py`.

2023-12-28 10:33 UTC, tturocy requested changes
I have made a few small comments.  However, because the test suite has been rewritten for `MixedBehaviorProfile` the tests aren't going to merge.  I would suggest making the changes on a new branch from latest `master`. - you should just be able to copy-paste in the changes in `game.pxi` and then write the test of creating with a given distribution in the new style.

2023-12-28 10:33 UTC, tturocy commented on src/pygambit/tests/test_behav.py
> +        self.profile_double = self.game.mixed_behavior_profile(None, rational=False)
The `None` here is unnecessary given that the `rational=` parameter name has been added

2023-12-28 10:33 UTC, tturocy commented on src/pygambit/tests/test_behav.py
> +    def test_probabilities_infoset_by_label_for_specific_distribution(self):
This test isn't necessary.

2023-12-28 10:33 UTC, tturocy commented on src/pygambit/tests/test_behav.py
> +    def test_normalize(self):
This test isn't necessary

2024-01-16 11:57 UTC, closed without merging