372 bug chance action probabilities after deleting chance action
gambitproject/gambit pull request #395
Opened 2023-10-26 13:49 UTC by rahulsavani

I haven't done a ChangeLog entry yet, but otherwise this is ready for review and possible merging

2023-10-27 09:46 UTC, tturocy requested changes
See the one improvement in terms of localising this change to `TreeGameRep` alone.  Otherwise this looks ready to merge - if you can squash and force-push first that'd certainly be helpful!

2023-10-27 09:46 UTC, tturocy commented on src/games/game.h
> +  /// Normalize the probability distribution of actions at a chance node
Having a separate `NormaliseChanceProbs` function makes sense, but it doesn't need to be a member of `GameRep`.  It just needs to be present in `TreeGameRep` as that's the only representation (at least at the moment) that implements the operation.   That means changes to the other representation classes can be rolled back.

Further, within `TreeGameRep`, this should be a private member function; there's no reason for external code to call this as having the probabilities be summing to one should already be maintained as an invariant.

2023-10-29 14:32 UTC, tturocy requested changes
You've accidentally added the .idea config files in the commit.  We do actually need to have a conversation about which ones we should include - because these can control things like static code checkers and formatters using those.  But that's something for another time!

2023-10-29 17:46 UTC, rahulsavani commented
> You've accidentally added the .idea config files in the commit. We do actually need to have a conversation about which ones we should include - because these can control things like static code checkers and formatters using those. But that's something for another time!

Yep I did a git add . a one point and apparently didn't clear up fully. That's been dealt with now and squashed.

2023-10-30 13:25 UTC, merged